### ISSUE TITLE
Remaining Km 

### ISSUE THREAD

**Issue by hajog68** [NikolasRupp/MMM-weconnectid#11]
Very nice Module - Thanks for providing !
I am using we connect with my VW Polo GTI (no "e" :-) )

The fields Odometer, Position etc. are working fine.
Just wondering if it is possilbe to also get the value for **remaining km** and the **% of fuel left** as those both values are displayed in the we connect app for your car. So the data is at least in the weconnect app existing.

![IMG_0011](https://github.com/NikolasRupp/MMM-weconnectid/assets/80542736/cf7e579f-eadb-431c-9e9a-09273bd56f50)

**Comment by NikolasRupp** [comment]
I think that the Cars without e have a different variable for the remaining km and fuel. I will have a Look when i have time. Maybe i need your Help to get the name. I will come back to you once I had a look

**Comment by hajog68** [comment]
Thanks and very happy to help 


Von der neuen AOL-App für iOS gesendet


Am Samstag, Mai 18, 2024, 12:59 PM schrieb NikolasRupp ***@***.***>:




I think that the Cars without e have a different variable for the remaining km and fuel. I will have a Look when i have time. Maybe i need your Help to get the name. I will come back to you once I had a look

**Comment by NikolasRupp** [comment]
Hi,
can you maybe send me your config for this module?
Please erase personal data like vin and so on.
And if it's possible can you please execute this code with the following comannd:
`python test.py -p Yourpassword -u YourEmail`
[test.zip](https://github.com/NikolasRupp/MMM-weconnectid/files/15385365/test.zip)
and then search for the variable that displays your remaining km and fuel tank and send me that part

**Comment by hajog68** [comment]
Hi Nikolas,
sure.By the way I am German, may you are as well ? So we can switch to German ?
Thanks in advance and I cross fingers that it will work.Happy to provide more, if needed.I also included a screenshot of the weconnect app
CheersHans

{
     disabled: false,
     module: 'MMM-weconnectid',
     position: "top_center",
     config: {
          username: "username",
          password: "passwort",
          vin: "WV....",
          fields: '{"Reichweite":"remainingKm","CLIMATE":"climatisation","KmStand":"odometer","Standort":"position","Breit":"latitude","Länge":"longitude"}',
          // fields_charging : ["LOADING TIME","TARGET SOC","LOADING POWER","KMPH"],
          number: 3,
          python: "python3.9",
          maxHeight: "300px",
          maxWidth: "800px",
          updateFrequency: 600000,
          timestamp: true,
          positions: [["Zuhause",49.xxxxx,8.xxxxx,200],["Work",50.xxxxx,6.xxxxx,300]]
     }
 },

**Comment by NikolasRupp** [comment]
Hi,
hast du es mal mit "gasolineRange" statt "remainingKm" probiert. Vielleicht löst das bereits das Problem. Kann aber sein , dass es das nur bei Hybridfahrzeugen gibt. Ansonsten mal bitte das oben genannte Programm ausführen damit man den Variablennamen herausfinden kann

**Comment by hajog68** [comment]
Works !"gasolineRange" works to display the remaining Km !Thanks a lot Now also the "non e-driver" can use your module as well.CheersHans
    Am Dienstag, 21. Mai 2024 um 15:00:59 MESZ hat NikolasRupp ***@***.***> Folgendes geschrieben:  
 
 


Hi,
hast du es mal mit "gasolineRange" statt "remainingKm" probiert. Vielleicht löst das bereits das Problem. Kann aber sein , dass es das nur bei Hybridfahrzeugen gibt. Ansonsten mal bitte das oben genannte Programm ausführen damit man den Variablennamen herausfinden kann

**Comment by hajog68** [comment]
Works !
"gasolineRange" works to display the remaining Km !
Thanks a lot 
Now also the "non e-driver" can use your module as well.
Cheers
Hans

**Comment by ChristopheHD** [comment]
Maybe we can update the README to indicates "gasolineRange" works also for non-electric vehicule.

**Comment by NikolasRupp** [comment]
Did that
