### ISSUE TITLE
(insecure_transport) OAuth 2 MUST utilize https.

### ISSUE THREAD

**Issue by ChrisF1976** [NikolasRupp/MMM-weconnectid#12]
Hello Nikolas,

when the module has started I see on the screen "(insecure_transport) OAuth 2 MUST utilize https." in the bottom line of the module. The vehicle pics do not update and also everything else does not update.

It started some days ago. So I waited some time if VW has a server issue.

So, there might be a general issue with the servers at VW. I don't get any errors from the module in the console. I think they changed something. 
I would appreciate it lot if you could check. I really love this module for my mirror :-)

Cheers, 
Chris.

![Bildschirmfoto 2024-11-30 um 19 15 53](https://github.com/user-attachments/assets/04bf1844-9ee5-4865-a393-cb54e07be9f9)

**Comment by NikolasRupp** [comment]
Hi,
It is a Problem with the WeConnect. Please have a look at this error to see if this solution works.
https://github.com/tillsteinbach/WeConnect-python/issues/217
Maybe you have to restart your Mirrow after that.

**Comment by ChrisF1976** [comment]
Yes, I just figured it out and wanted to tell you that the topic can be closed!
My id4 was back since yesterday. I remembered that I accepted some new terms and conditions. I just told my wife and she did the same. Now it is fixed. Unbelievable error. I'm wondering that the whole car should have had an error, but there it was okay.
Thanks for your quick reply!!!!
