### ISSUE TITLE
No module named weconnect

### ISSUE THREAD

**Issue by berndwillebrandt0** [NikolasRupp/MMM-weconnectid#13]
Hello, I installed weconnect according to the instructions. The error message appears in the MagicMirror screen: No modules named weconnect. Please install it via Pit. Unfortunately I can't find the error

**Comment by NikolasRupp** [comment]
Hi,
Can you Tell me what you did exactly and send me your config for the module. Please remove any sensible data

**Comment by berndwillebrandt0** [comment]
[config.txt](https://github.com/user-attachments/files/18081774/config.txt)

**Comment by berndwillebrandt0** [comment]
I did everything according to the instructions, How can I check this?

**Comment by berndwillebrandt0** [comment]
![weconnect](https://github.com/user-attachments/assets/9e219991-059a-4daa-a33d-789dcc5b0252)

**Comment by berndwillebrandt0** [comment]
admin@spiegel:~ $ pip show weconnect
Name: weconnect
Version: 0.60.6
Summary: Python API for the Volkswagen WeConnect Services
Home-page: https://github.com/tillsteinbach/WeConnect-python
Author: Till Steinbach
Author-email:
License: MIT
Location: /home/admin/.local/lib/python3.9/site-packages
Requires: oauthlib, requests
Required-by:
admin@spiegel:~ $

**Comment by berndwillebrandt0** [comment]
admin@spiegel:~ $ python
Python 3.11.2 (main, Sep 14 2024, 03:00:30) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import weconnect
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'weconnect'

**Comment by NikolasRupp** [comment]
Can you do 
`python -m pip show weconnect`

**Comment by berndwillebrandt0** [comment]
admin@spiegel:~ $ python -m pip show weconnect
WARNING: Package(s) not found: weconnect
admin@spiegel:~ $

**Comment by NikolasRupp** [comment]
Okay. And
`python3 -m pip show weconnect`

**Comment by berndwillebrandt0** [comment]
admin@spiegel:~ $ python3 -m pip show weconnect
WARNING: Package(s) not found: weconnect

**Comment by NikolasRupp** [comment]
It seems you pip refers to some other python version. Please do 
```
python3 -m pip install Pillow
python3 -m pip install weconnect[Images]
```

PS: I deleted your config because it had very sensitive data in it

**Comment by berndwillebrandt0** [comment]
admin@spiegel:~ $ python3 -m pip install Pillow
error: externally-managed-environment

This environment is externally managed

To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.

If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.

For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Comment by NikolasRupp** [comment]
Can you do 
```
python -m pip install Pillow
python -m pip install weconnect[Images]
```

**Comment by berndwillebrandt0** [comment]
the same problem:
admin@spiegel:~ $ python -m pip install Pillow
error: externally-managed-environment

This environment is externally managed

**Comment by NikolasRupp** [comment]
Can you show me the results of
```
which -a python
which -a pip
```

**Comment by berndwillebrandt0** [comment]
admin@spiegel:~ $ which -a python
/usr/bin/python
/bin/python

**Comment by berndwillebrandt0** [comment]
admin@spiegel:~ $ which -a pip
/home/admin/.local/bin/pip
/usr/bin/pip
/bin/pip
admin@spie

**Comment by NikolasRupp** [comment]
Which Raspberry OS have you installed? Bookworm?
You can check it by using
`cat /etc/os-release`

**Comment by berndwillebrandt0** [comment]
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by berndwillebrandt0** [comment]
Is it wrong?

**Comment by NikolasRupp** [comment]
Okay since this version it's not that simple to install packages system wide. The easiest way is to override the managed environment error. You can do it by using this
```
python3 -m pip install Pillow --break-system-packages
python3 -m pip install weconnect[Images] --break-system-packages
```
Another way would be by using a virtual environment

**Comment by berndwillebrandt0** [comment]
admin@spiegel:~ $ python3 -m pip install Pillow --break-system-packages
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (9.4.0)
admin@spiegel:~ $ python3 -m pip install weconnect[Images] --break-system-packages
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting weconnect[Images]
  Using cached weconnect-0.60.6-py3-none-any.whl (167 kB)
Collecting requests~=2.32.3
  Using cached https://www.piwheels.org/simple/requests/requests-2.32.3-py3-none-any.whl (64 kB)
Requirement already satisfied: oauthlib~=3.2.2 in /usr/lib/python3/dist-packages (from weconnect[Images]) (3.2.2)
Collecting pillow~=10.4.0
  Using cached pillow-10.4.0-cp311-cp311-manylinux_2_28_aarch64.whl (4.4 MB)
Collecting ascii_magic~=2.3.0
  Using cached https://www.piwheels.org/simple/ascii-magic/ascii_magic-2.3.0-py3-none-any.whl (729 kB)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from ascii_magic~=2.3.0->weconnect[Images]) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3/dist-packages (from requests~=2.32.3->weconnect[Images]) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests~=2.32.3->weconnect[Images]) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests~=2.32.3->weconnect[Images]) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests~=2.32.3->weconnect[Images]) (2022.9.24)
Installing collected packages: requests, pillow, weconnect, ascii_magic
Successfully installed ascii_magic-2.3.0 pillow-10.4.0 requests-2.32.3 weconnect-0.60.6

**Comment by berndwillebrandt0** [comment]
admin@spiegel:~ $ python3 -m pip show weconnect
Name: weconnect
Version: 0.60.6
Summary: Python API for the Volkswagen WeConnect Services
Home-page: https://github.com/tillsteinbach/WeConnect-python
Author: Till Steinbach
Author-email:
License: MIT
Location: /home/admin/.local/lib/python3.11/site-packages
Requires: oauthlib, requests
Required-by:

**Comment by NikolasRupp** [comment]
Do you still have the same error on your mirror?

**Comment by berndwillebrandt0** [comment]
must i reboot?

**Comment by NikolasRupp** [comment]
Yeah maybe. If you use p,2 you can also use. 
`pm2 restart mm`

**Comment by berndwillebrandt0** [comment]
its ocay thanks

**Comment by NikolasRupp** [comment]
So it's working?

**Comment by berndwillebrandt0** [comment]
very good
thank you so mutch

**Comment by NikolasRupp** [comment]
No Problem
