### ISSUE TITLE
insecure transport

### ISSUE THREAD

**Issue by hajog68** [NikolasRupp/MMM-weconnectid#14]
Hello Nikolas,

Since approx. 1 week for some reason the module shows no real car data any more.
I haven't changed anything in the car (e.g. security settings) nor in my magic mirror installation (except some regular system updates "sudo apt update & upgrade").
You can see the error message “insecure transport…… https” on the screen, which unfortunately does not speak to me 😊
Cheers
Hans

![IMG_0623](https://github.com/user-attachments/assets/90431a47-1723-42b1-bb4f-e4e38d27393c)

**Comment by NikolasRupp** [comment]
Hi,
Please have a look at Issue https://github.com/NikolasRupp/MMM-weconnectid/issues/12.
You have to log in on the web to accept the new Terms and Conditions.

**Comment by hajog68** [comment]
Oh, wow - thanks a lot and sorry :-)
    Am Dienstag, 10. Dezember 2024 um 16:47:55 MEZ hat NikolasRupp ***@***.***> Folgendes geschrieben:   

 


Hi,
Please have a look at Issue #12.
You have to log in on the web to accept the new Terms and Conditions.

**Comment by NikolasRupp** [comment]
No Problem. Hope this is fixed. If not please reopen it

**Comment by hajog68** [comment]
It works fine now and as before !
    Am Dienstag, 10. Dezember 2024 um 17:01:39 MEZ hat NikolasRupp ***@***.***> Folgendes geschrieben:   

 


No Problem. Hope this is fixed. If not please reopen it
