### ISSUE TITLE
Lade...

### ISSUE THREAD

**Issue by berndwillebrandt0** [NikolasRupp/MMM-weconnectid#15]
I have another problem when restarting this morning. Only Loading... is displayed 

![weconnect 1](https://github.com/user-attachments/assets/23df29b8-227f-4461-a242-aa26d7549e0d)

Name: weconnect
Version: 0.60.6
Summary: Python API for the Volkswagen WeConnect Services
Home-page: https://github.com/tillsteinbach/WeConnect-python
Author: Till Steinbach
Author-email:
License: MIT
Location: /home/admin/.local/lib/python3.11/site-packages
Requires: oauthlib, requests
Required-by:

**Comment by berndwillebrandt0** [comment]
sorry,

**Comment by berndwillebrandt0** [comment]
sorry, running again

**Comment by hajog68** [comment]
:-) I have today exactly the same problem "lade" (loading). Yesterday all worked fine
@ Bernd: How did you fixed it ?

**Comment by NikolasRupp** [comment]
I think it's no real error. It just means, that it can't fetch the Info because it does not get a response vom VW. Maybe the API is a bit slow today. :) 
Can you maybe restart your mirror? I probably have to implement a timeout if i have time.

**Comment by NikolasRupp** [comment]
Just to be sure. Do you use the google maps api or not?

**Comment by hajog68** [comment]
Thanks again....Already restarted a few times, same effect "loading..."But I just be patient :-)
Regarding google mapsI do not use the google api feature, this config line is missing in my config of the module.



    Am Donnerstag, 12. Dezember 2024 um 13:13:01 MEZ hat NikolasRupp ***@***.***> Folgendes geschrieben:   

 


Just to be sure. Do you use the google maps api or not?

**Comment by NikolasRupp** [comment]
Can you open a termil window, go inside the MMM-weconnectid folder and do
`python3 api.py {your email} {your password} {vin} ./Pictures`
and send me the response

**Comment by hajog68** [comment]
the response was:

/vehicles/WVxxxxxxxxxxxxx23/trips/shortTerm: Unknown attribute totalFuelConsumption_L with value 0.64
/vehicles/WVxxxxxxxxxxxxx23/trips/longTerm: Unknown attribute totalFuelConsumption_L with value 283.92
/vehicles/WVxxxxxxxxxxxxx23/trips/cyclic: Unknown attribute totalFuelConsumption_L with value 8.91
{'status': 0, 'error': '[Errno 2] No such file or directory: WVxxxxxxxxxxx23/car.png'}


I changed my vin with "xxx" in the middle

**Comment by hajog68** [comment]
belive it or not, now it works fine again ....hmmm ?
Thanks a lot for your support !!!

**Comment by NikolasRupp** [comment]
Strange. Please open again if it's not working
