### ISSUE TITLE
UI loaded, but no data

### ISSUE THREAD

**Issue by EdAmcore** [NikolasRupp/MMM-weconnectid#3]
Hello and Guten Tag,
after I bought a second hand ID.3 1st and the "weconnect" packages from VW are activated, I wanted to show data of the car on the MagicMirror, because not every one likes to check the car via the smartphone app. I think that everything went fine, but there is no data shown on the UI.
Data connection via the VW app is working.
I use MagicMirror 2.26.0 on a Raspi 3+. OS is Raspberry Pi OS 32-Bit Legacy from 2023. Python was installed 3.9.2 and I installed like in your doc mentioned 3.9.15.
Please help @NikolasRupp where can I check, whats wrong?
Thanks and regards!

**Comment by NikolasRupp** [comment]
So is there nothing to see on the Screen or how does it Look Like when it's running? Could you maybe send me a picture of what it looks Like, if there is anything?

**Comment by EdAmcore** [comment]
![2024-01-15 Screen](https://github.com/NikolasRupp/MMM-weconnectid/assets/156408030/cea117e8-f340-4264-882b-8a1ee140ad15)
Screenshot: Bottom/Left the weconnect part

**Comment by NikolasRupp** [comment]
So the Problem seem to be that you run it on  32-Bit.
I made a small change. Could you please pull it again and then retry it.
You won't be able to see the timestamp from the last update of the car. I have to find a solution for that. But i can't really test it at the moment because i don't have a rpi and can only run it in an windows envirenment which has 64-Bit. My rpi will arrive later this week. Maybe I will then have time to test it

**Comment by EdAmcore** [comment]
![image](https://github.com/NikolasRupp/MMM-weconnectid/assets/156408030/62a0bcdd-c80a-4606-9474-e8e4e21bec35)
Okay, now another text. I checked once more my login/pass and vin from the config.js file at the VW-DE site. This is okay. Maybe something to do on the VW homepage? I could wait until friday/weekend, if it's more easy for you.

**Comment by NikolasRupp** [comment]
Okay this seems strange. I never came across this. I think you live in Austria right? Unfortunately I can only test this for germany. 
If youl ive in Autria do you login in web via 
https://www.myvolkswagen.net/at/de/myvolkswagen.html
or
https://www.volkswagen.de/de/besitzer-und-nutzer/myvolkswagen.html?

Maybe this is the Problem. But I will have a deeper look into this once my rpi is here

**Comment by NikolasRupp** [comment]
Okay sorry it seems this does not come from the vw api but from the google one. Do you use the "googleAPI" parameter. If so please try it without it

**Comment by EdAmcore** [comment]
![image](https://github.com/NikolasRupp/MMM-weconnectid/assets/156408030/cee4f2ea-b95f-40fa-be0a-251b6e26f728)
Yes, Google API caused the problem. Deleted the API String and everything okay! Nice! Really don't need the exact position of the car. Thanks for the help!
Grüße aus Niederösterreich!

**Comment by NikolasRupp** [comment]
Okay perfect. Happy to help.
